event schema created
kir-dev/programSCH pull request #1
Opened 2024-05-02 16:56 UTC by justnyx

Megcsináltam az event sémát

2024-05-02 17:15 UTC, mozsarmate reviewed
osszessegeben nyomod

2024-05-02 17:15 UTC, mozsarmate commented on prisma/schema.prisma
> +}
Lehetne a Prio-knak valami kifejezobb neve. Pl.: Haz szintu rendezveny, Reszortos, stb..

2024-05-02 17:15 UTC, mozsarmate commented on prisma/schema.prisma
> +  organizedEvents Event[] @relation("organizers")
@relation("owner") - szerintem ez nem kell

2024-05-02 17:15 UTC, mozsarmate commented on prisma/schema.prisma
> +  organizedEvents Event[] @relation("organizers")
meg akkor ugye az eventbe se kene az "owner", csak a relation tobbi attributeja

2024-05-02 17:16 UTC, mozsarmate approved these changes

2024-05-02 17:19 UTC, justnyx commented on prisma/schema.prisma
> +}
az lehet, csak akk meg kéne majd beszélni, hogy mik legyenek

2024-05-02 17:24 UTC, justnyx commented on prisma/schema.prisma
> +}
vagy akkor ne priority legyen, hanem event type, vagy valami hasonló

2024-05-02 17:27 UTC, justnyx commented on prisma/schema.prisma
> +}
de amúgy egyáltalán mi értelme van a prionak? milyen plusz infot ad, amit a tagekből nem lehet leszűrni?

2024-05-03 09:00 UTC, mozsarmate commented on prisma/schema.prisma
> +}
azert hasznos, hogy van prio, mert igy ha tobb rendezveny kozul kell donteni, hogy melyik legyen mondjuk feljebb a naptarban, vagy nagyobb blokkban, akkor az igy egyszeru lenne

de jaja, megbeszelhetjuk majd, hogy mik legyenek a nevek, meg ez amugy is csak ilyen szorszalhasogatas

2024-05-03 15:14 UTC, DannySS123 requested changes
Szuper kezdés, annyi hogy a prisma séma fájl már létezik a backend/prisma mappában, oda át tudnád rakni? :D

2024-05-03 15:29 UTC, justnyx commented
Ja sry nem láttam, majd átrakom.

2024-05-05 17:03 UTC, DannySS123 approved these changes
Jó lesz, az event ID kicsit szebb lenne ha egy random string lenne (mert az biztonságosabb), pl így: 
  `id          String   @id @default(uuid())`

2024-05-06 16:48 UTC, merged