Event crud
kir-dev/programSCH pull request #13
Opened 2024-05-11 21:03 UTC by justnyx

Implemented CRUD functionality for the Event model

2024-05-14 14:04 UTC, DannySS123 commented on package-lock.json
Ezt kérlek töröld, ne használjunk npm installt, az csinál package-lock filet. Maradjunk a yarn nál

2024-05-14 14:23 UTC, DannySS123 commented on apps/backend/src/event/dto/create-event.dto.ts
> +// eslint-disable-next-line @typescript-eslint/ban-ts-comment
Ez a komment okkal van itt vagy csak itt maradt? Szerintem nem kell

2024-05-14 14:23 UTC, DannySS123 commented on apps/backend/src/event/dto/update-event.dto.ts
> +// eslint-disable-next-line @typescript-eslint/ban-ts-comment
ez sem kell

2024-05-14 14:24 UTC, DannySS123 requested changes
Szép munka 💯 🔥 
Pár kommentet hagytam, amúgy jó lesz :D

2024-05-17 12:57 UTC, DannySS123 approved these changes
👌

2024-05-19 15:50 UTC, Tschonti commented on package.json
> +  }
these dependencies won't be used by the frontend app, so they should be in the package.json inside the apps/backend dir. Delete them from here, and execute the yarn add ... command from the apps/backend dir

2024-05-19 15:51 UTC, Tschonti commented on apps/backend/src/event/event.module.ts
> +  imports: [PrismaModule.forRoot({ isGlobal: true })],
There's no need to import PrismaModule again. It's imported in the app.module with the isGlobal flag, so it's available throughout the project

2024-05-21 18:20 UTC, merged